class Vehicle {
  final int? id;  // Auto-generated by SQLite
  final String vin;
  final String make;
  final String model;
  final String year;
  final String engine;
  final String createdAt;

  Vehicle({
    this.id, 
    required this.vin, 
    required this.make, 
    required this.model, 
    required this.year, 
    required this.engine,
    required this.createdAt,
  });

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'vin': vin,
      'make': make,
      'model': model,
      'year': year,
      'engine': engine,
      'createdAt': createdAt,
    };
  }

  factory Vehicle.fromMap(Map<String, dynamic> map) {
    return Vehicle(
      id: map['id'],
      vin: map['vin'],
      make: map['make'],
      model: map['model'],
      year: map['year'],
      engine: map['engine'],
      createdAt: map['createdAt'],
    );
  }
}