class Vehicle {
  final int? id;  // Auto-generated by SQLite
  final String vin;
  final String make;
  final String model;
  final String year;
  final String car;
  final String? mileage;
  final String? lastMaintenanceService;
  final String createdAt;

  Vehicle({
    this.id, 
    required this.vin, 
    required this.make, 
    required this.model, 
    required this.year, 
    required this.car,
    this.mileage,
    this.lastMaintenanceService,
    required this.createdAt,
  });

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'vin': vin,
      'make': make,
      'model': model,
      'year': year,
      'car': car,
      'mileage': mileage,
      'lastMaintenanceService': lastMaintenanceService,
      'createdAt': createdAt,
    };
  }

  factory Vehicle.fromMap(Map<String, dynamic> map) {
    return Vehicle(
      id: map['id'],
      vin: map['vin'],
      make: map['make'],
      model: map['model'],
      year: map['year'],
      car: map['car'],
      mileage: map['mileage'],
      lastMaintenanceService: map['lastMaintenanceService'],
      createdAt: map['createdAt'],
    );
  }
}